on:
  workflow_call:

env:
  BASE_BRANCH: main

jobs:
  build-gdextension:
    runs-on: ${{ matrix.opts.runner }}
    name: ${{ matrix.opts.name }}
    strategy:
      fail-fast: false
      matrix:
        opts:
          - identifier: linux-debug (x86_64)
            name: Linux (x86_64) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: linux-release (x86_64)
            name: Linux (x86_64) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: linux
            arch: x86_64
          - identifier: linux-debug (x86_32)
            name: Linux (x86_32) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: linux
            arch: x86_32
          - identifier: linux-release (x86_32)
            name: Linux (x86_32) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: linux
            arch: x86_32

          - identifier: windows-debug (x86_64)
            name: Windows (x86_64) - template_debug
            runner: windows-latest
            target: template_debug
            platform: windows
            arch: x86_64
          - identifier: windows-release (x86_64)
            name: Windows (x86_64) - template_release
            runner: windows-latest
            target: template_release
            platform: windows
            arch: x86_64
          - identifier: windows-debug (x86_32)
            name: Windows (x86_32) - template_debug
            runner: windows-latest
            target: template_debug
            platform: windows
            arch: x86_32
          - identifier: windows-release (x86_32)
            name: Windows (x86_32) - template_release
            runner: windows-latest
            target: template_release
            platform: windows
            arch: x86_32

          - identifier: macos-release (universal)
            name: MacOS (universal) - template_release
            runner: macos-latest
            target: template_release
            platform: macos
            arch: universal
          - identifier: macos-debug (universal)
            name: MacOS (universal) - template_debug
            runner: macos-latest
            target: template_debug
            platform: macos
            arch: universal

          - identifier: android-release (arm64)
            name: Android (arm64) - template_release
            runner: ubuntu-20.04
            target: template_release
            platform: android
            arch: arm64
          - identifier: android-debug (arm64)
            name: Android (universal) - template_debug
            runner: ubuntu-20.04
            target: template_debug
            platform: android
            arch: arm64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install gcc-multilib
        if: ${{ startsWith(matrix.opts.arch, 'x86_32') && startsWith(matrix.opts.runner,'ubuntu-') }}
        shell: sh
        run: |
          sudo apt-get update
          sudo apt install gcc-multilib g++-multilib
      
      - name: (Linux) Install buildroot x86_64
        if: ${{ startsWith(matrix.opts.identifier, 'linux-') && contains(matrix.opts.arch, 'x86_64')}}
        shell: sh
        run: |
          sudo update-ca-certificates -v
          sudo apt-get update
          sudo apt-get install yasm
          cd /opt
          curl -LO -k https://downloads.tuxfamily.org/godotengine/toolchains/linux/2021-02-11/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar xf x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          rm -f x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
          mv x86_64-godot-linux-gnu_sdk-buildroot buildroot
          cd buildroot
          ./relocate-sdk.sh
      
      - name: (Linux) Install buildroot x86_32
        if: ${{ startsWith(matrix.opts.identifier, 'linux-') && contains(matrix.opts.arch, 'x86_32')}}
        shell: sh
        run: |
          sudo update-ca-certificates -v
          sudo apt-get update
          sudo apt-get install yasm
          cd /opt
          curl -LO -k https://downloads.tuxfamily.org/godotengine/toolchains/linux/2021-02-11/i686-godot-linux-gnu_sdk-buildroot.tar.bz2
          tar xf i686-godot-linux-gnu_sdk-buildroot.tar.bz2
          rm -f i686-godot-linux-gnu_sdk-buildroot.tar.bz2
          mv i686-godot-linux-gnu_sdk-buildroot buildroot
          cd buildroot
          ./relocate-sdk.sh
          
      #- name: (Android) Set up Java 11
      #  if: ${{ startsWith(matrix.opts.identifier, 'android-') }}
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 11
      #
      #- name: (Android) Set up Android SDK
      #  if: ${{ startsWith(matrix.opts.identifier, 'android-') }}
      #  uses: android-actions/setup-android@v2
      #
      #- name: (Android) Install Android Tools
      #  if: ${{ startsWith(matrix.opts.identifier, 'android-') }}
      #  shell: sh
      #  run: |
      #    "$ANDROID_SDK_ROOT"/cmdline-tools/latest/bin/sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version
          
      - name: Load .scons_cache directory
        id: godot-extension-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{env.BASE_BRANCH}}
            
      - name: Compile extension
        shell: sh
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          SCONS_CACHE_LIMIT: 7168
        run: |
          PATH=/opt/buildroot/bin:$PATH scons target='${{ matrix.opts.target }}' platform='${{ matrix.opts.platform }}' arch='${{ matrix.opts.arch }}' ${{ matrix.opts.args }} -j2
          ls -la demo/addons/godotgif/bin/
      - name: Strip bins
        if: "!startsWith(matrix.opts.identifier, 'windows-') && startsWith(matrix.opts.arch, 'x86_')"
        shell: sh
        run: |
          strip demo/addons/godotgif/bin/*
      - name: Prepare artifact
        shell: sh
        run: |
          mkdir -p project/addons/godotgif
          mv demo/addons/godotgif/* project/addons/godotgif

          cd project/addons/godotgif
          rm -rf 'godotgif.gdextension' || true
          cd ./bin
          rm -rf *.exp *.lib || true
          cd ../../../..

          (cp -n 'README.md' 'LICENSE.txt' 'godotgif.gdextension' project/addons/godotgif) || true
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gdextension
          path: |
            project/
